Updated flatbuffer sequence

diff --git a/CREATE b/CREATE
--- a/CREATE
+++ b/CREATE
@@ -236,6 +236,7 @@ COMPILE_PROJECT=false
 BUILD_PROJECT_EARTHLY=true
 FLATBUFFER_CLEAN=false
 HEADLESS=OFF
+TESTS=OFF
 
 # Enhanced option parsing
 while [[ "$#" -gt 0 ]]; do
@@ -265,6 +266,7 @@ while [[ "$#" -gt 0 ]]; do
          shift ;;
         -h|--help) display_help ;;
         --headless) HEADLESS=ON; shift ;;
+        --tests) TESTS=ON; shift ;;
         *) echo "${Yellow}================================================================================${Reset}\n${Red}Unknown option: $1${Reset}"; display_help; exit 1 ;;
     esac
 done
@@ -368,7 +370,7 @@ if [[ "$COMPILE_PROJECT" == true ]]; then
   echo "${BoldBlue}[Build]${Reset} ${Green}Configuring with CMake...${Reset}"
   echo "${Yellow}================================================================================${Reset}"
   echo "${BoldBlue}********************************************************************************${Reset}"
-  cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DHEADLESS=$HEADLESS ${COMPILER:+-DCMAKE_CXX_COMPILER=$COMPILER} || { echo "CMake configuration failed"; exit 1; }
+  cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DHEADLESS=$HEADLESS -DRUN_TESTS=$TESTS ${COMPILER:+-DCMAKE_CXX_COMPILER=$COMPILER} || { echo "CMake configuration failed"; exit 1; }
   echo "${Yellow}================================================================================${Reset}"
   echo "${BoldBlue}[Build]${Reset} ${Green}Building with CMake...${Reset}"
   echo "${Yellow}================================================================================${Reset}"
